/* Auto-generated by frap_table_generator.py */
#pragma once

#include <stdint.h>

struct frap_cfg_entry {
    const char *name; /* task name / label */
    int resid;
    int spin_prio; /* numeric priority */
    int pid_hint; /* optional hint used by demo */
};

static const struct frap_cfg_entry frap_generated_table[] = {
    { "hot0", 0, 240, 0 },
    { "hot0", 1, 240, 0 },
    { "hot1", 0, 238, 1 },
    { "hot1", 1, 239, 1 },
    { "mid0", 0, 200, 2 },
    { "mid0", 2, 200, 2 },
    { "mid1", 2, 190, 3 },
    { "mid1", 3, 199, 3 },
    { "remoteA0", 1, 240, 4 },
    { "remoteA1", 1, 119, 5 },
    { "remoteA1", 3, 119, 5 },
    { "remoteB0", 1, 240, 6 },
    { "background", 3, 114, 7 },
    { "mid0", 1, 239, 2 },
    { "mid1", 1, 239, 3 },
    { "hot1", 3, 239, 1 },
    { "mid0", 3, 237, 2 },
};

static const int frap_generated_table_len = sizeof(frap_generated_table)/sizeof(frap_generated_table[0]);
